questions:
  label:  laminsanneh.fantasticfaq::lang.controller.questions
  list: @/plugins/laminsanneh/fantasticfaq/models/question/columns.yaml
  form: @/plugins/laminsanneh/fantasticfaq/models/question/fields.yaml