# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: laminsanneh.fantasticfaq::lang.controller.faqgroup

# Model Form Field configuration
form: @/plugins/laminsanneh/fantasticfaq/models/faqgroup/fields.yaml

# Model Class name
modelClass: LaminSanneh\FantasticFaq\Models\FaqGroup

# Default redirect location
defaultRedirect: laminsanneh/fantasticfaq/faqgroups

# Create page
create:
    title: laminsanneh.fantasticfaq::lang.controller.createfaqgroups
    redirect: laminsanneh/fantasticfaq/faqgroups/update/:id
    redirectClose: laminsanneh/fantasticfaq/faqgroups

# Update page
update:
    title: laminsanneh.fantasticfaq::lang.controller.editfaqgroups
    redirect: laminsanneh/fantasticfaq/faqgroups
    redirectClose: laminsanneh/fantasticfaq/faqgroups

# Preview page
preview:
    title: laminsanneh.fantasticfaq::lang.controller.previewfaqgroups